apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-webapp
  name: hello-webapp
  namespace: ${PROD_NAMESPACE}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-webapp
  template:
    metadata:
      labels:
        app: hello-webapp
    spec:
      containers:
              - image: ${appImage}:${IMAGE_TAG}
        name: hello-webapp
        stdin: true
