apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-webapp
  name: hello-webapp
  namespace: hello-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-webapp
  template:
    metadata:
      labels:
        app: hello-webapp
    spec:
      containers:
      - image: asendzhingarov/hello-webapp:1.12
        name: hello-webapp
        stdin: true
