apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-webapp-svc
  name: hello-webapp-svc
  namespace: hello-webapp
spec:
  ports:
  - name: 8001-8081
    port: 8001
    protocol: TCP
    targetPort: 8081
  selector:
    app: hello-webapp
  type: NodePort
